CREATE TABLE [dbo].[Buyer]
(
	ID			INT IDENTITY (1,1) NOT NULL,
	Name		NVARCHAR(30) NOT NULL,
	CONSTRAINT [PK_dbo.Buyer] PRIMARY KEY CLUSTERED (ID ASC)
);

CREATE TABLE [dbo].[Seller]
(
	ID			INT IDENTITY (1,1) NOT NULL,
	Name		NVARCHAR(30) NOT NULL,
	CONSTRAINT [PK_dbo.Seller] PRIMARY KEY CLUSTERED (ID ASC)
);

CREATE TABLE [dbo].[Item]
(
	ID			INT IDENTITY (1001,1) NOT NULL,
	Name		NVARCHAR(30) NOT NULL,
	Description NVARCHAR(254) NOT NULL,
	Seller		INT NOT NULL,
	CONSTRAINT [PK_dbo.Item] PRIMARY KEY CLUSTERED (ID ASC),
	CONSTRAINT [FK_dbo.Item] FOREIGN KEY (Seller) REFERENCES [dbo].[Seller] (ID) ON DELETE CASCADE ON UPDATE CASCADE

);

CREATE TABLE [dbo].[Bid]
(
	ID			INT IDENTITY (1,1) NOT NULL,
	Item		INT NOT NULL,
	Buyer		INT NOT NULL,
	Price		INT NOT NULL,
	TimeStamp	DATETIME NOT NULL
	CONSTRAINT [PK_dbo.Bid] PRIMARY KEY CLUSTERED (ID ASC),
	CONSTRAINT [FK_dbo.Bid] FOREIGN KEY (Item) REFERENCES [dbo].[Item] (ID),
	CONSTRAINT [FK2_dbo.Bid] FOREIGN KEY (Buyer) REFERENCES [dbo].[Buyer] (ID)

);

